# 워크플로우 이름
name: KACG Spring CI/CD

# 워크플로우 실행 조건
on:
  # 1. main 또는 develop 브랜치에 push 이벤트가 발생했을 때
  push:
    branches: [ "main", "develop" ]
  # 2. main 또는 develop 브랜치를 대상으로 Pull Request가 생성/수정되었을 때
  pull_request:
    branches: [ "main", "develop" ]

# 환경 변수 설정
env:
  # 소문자 규칙을 준수하는 이미지 이름 설정
  IMAGE_NAME: ghcr.io/devcourse-kacg/kacg_cicd_hj

jobs:
  # ========================
  # CI Job: 테스트 및 빌드
  # ========================
  build-and-test:
    # Pull Request일 때만 이 Job을 실행
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    
    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      # 3. Gradle 캐싱 설정 (빌드 속도 향상)
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      # 4. Gradle 실행 권한 부여
      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      # 5. Gradle로 테스트 실행
      - name: Test with Gradle
        run: ./gradlew test

      # 6. Gradle로 빌드 실행
      - name: Build with Gradle
        run: ./gradlew build
        
  # ========================
  # CD Job: 이미지 빌드 및 배포
  # ========================
  build-and-deploy:
    # push 이벤트일 때만 이 Job을 실행
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    # 이전 Job이 필요하지 않으므로 needs를 사용하지 않음
    
    steps:
      # 1. 소스 코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v4

      # 2. 이미지 태그 설정 (main 브랜치는 latest, develop 브랜치는 develop)
      - name: Set image tag
        run: |
          if [ "${{ github.ref }}" = "refs/heads/main" ]; then
            echo "IMAGE_TAG=latest" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=develop" >> $GITHUB_ENV
          fi

      # 3. GHCR 로그인
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PAT }}

      # 4. Docker 이미지 빌드 및 푸시
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

      # 5. SSH를 통해 EC2에 접속하여 배포
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            # EC2에서 GHCR 로그인
            echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
            
            # 기존 컨테이너 중지 및 삭제 (오류 무시)
            docker rm -f my-spring-app || true
            
            # 최신 이미지 pull
            docker pull ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            
            # 새 컨테이너 실행
            docker run -d \
              --name my-spring-app \
              --restart unless-stopped \
              --network common \
              -p 8080:8080 \
              -e DB_URL="jdbc:mysql://mysql_1:3306/${{ secrets.DB_NAME }}" \
              -e DB_USERNAME="lldj" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e SPRING_CLOUD_AWS_S3_BUCKET="${{ secrets.S3_BUCKET }}" \
              -e JWT_SECRET_KEY="${{ secrets.JWT_SECRET_KEY }}" \
              -e FRONTEND_BASE_URL="${{ secrets.FRONTEND_BASE_URL }}" \
              ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

            # 사용하지 않는 Docker 이미지 정리 (디스크 용량 확보)
            docker image prune -f
